import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { config } from 'dotenv';
import manifest from "./manifest.json" assert { type: "json" };

config();

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
let outdir = "./";
if (!prod) {
	const vaultDir = process.env.LINKED_VAULT
	// process.env.REAL === "1" ? process.env.REAL_VAULT : process.env.TEST_VAULT;
	outdir = `${vaultDir}/.obsidian/plugins/${manifest.id}`;
}

console.info(`\nSaving plugin to ${outdir}\n`);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	minify: prod ? true : false,
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: outdir,
	outbase: "./src",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}